PasswordGame/PasswordGame/Models/ErrorViewModel.cs
namespace PasswordGame.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

PasswordGame/PasswordGame/Models/GameViewModel.cs
using Newtonsoft.Json;
using System.Linq;
using System.Text.Json.Serialization;
using System.Text.RegularExpressions;

namespace PasswordGame.Models
{
    public class GameViewModel
    {
        public bool IsPasswordComplete { get; set; }
        public int LastRule { get; set; } = 1;
        public string HtmlResult {get; set;}
        
        public List<Rule> Rules => new List<Rule>()
        {
                new Rule("Your password must have more than 5 symbols!",CheckLengthBy5 ),
                new Rule("Your password must have digit!",CheckByDigit),
                new Rule("Your password must have capital letter!",CheckByCapitalLetter),
                new Rule("Your password must have special symbol!",CheckBySpecialSymbol),
                new Rule("Your password must have digits count equal to 25  !",CheckDigitsCount25),
                new Rule("Your password must have month name in English!",CheckMonthInEnglish),
                new Rule("Your password must have current time of Tokyo!",CheckTokyoTime),
        };
        private bool CheckTokyoTime(string password)
        {
            var response = CheckTokyoTimeAsync(password);
            response.Wait();
            return response.Result;
            async Task<bool> CheckTokyoTimeAsync(string password)
            {
                TimeApiResponse apiResponse = new TimeApiResponse();

                using (HttpClient client = new HttpClient())
                {
                    string urlApi = "https://www.timeapi.io/api/Time/current/zone?timeZone=Asia/Tokyo";
                    var response = await client.GetAsync(urlApi);

                    if (response.IsSuccessStatusCode)
                    {
                        string responseString = await response.Content.ReadAsStringAsync();
                        apiResponse = JsonConvert.DeserializeObject<TimeApiResponse>(responseString);
                        Console.WriteLine("Time in Tokyo: " + apiResponse.hour);
                    }
                }

                return password.Contains(apiResponse.hour.ToString());

            }
        }
        

        private bool CheckMonthInEnglish(string password)
        {
            return Regex.IsMatch(password, @"(January|February|March|April|May|June|July|August|September|October|November|December)", RegexOptions.IgnoreCase);
        }

        public bool CheckLengthBy5(string password)
        {
            return password.Length>5;
        }
        public bool CheckByDigit(string password)
        {
            return password.Any(char.IsDigit);
        }
        public bool CheckByCapitalLetter(string password)
        {
            return Regex.IsMatch(password, @"[A-Z]");
        }
        public bool CheckBySpecialSymbol(string password)
        {
            return Regex.IsMatch(password, @"[/!@#$%^&*()_+\-=\\{};':""\\|,.<>\/?+/]");
        }
        public bool CheckDigitsCount25(string password)
        {
            var digits = password.Where(char.IsDigit);
            int sum = digits.Sum(c => int.Parse(c.ToString()));
            return  sum == 25;
        }
    }
    public class  Rule
    {
        /// <summary>
        /// This delegate for getting methods for constructor
        /// </summary>
        /// <param name="password">password</param>
        /// <returns>true or false</returns>
        public delegate bool RuleCheck(string password);

        /// <summary>
        /// Info
        /// </summary>
        public string Text {get; set;}
        public RuleCheck Action {get; set;}

        /// <summary>
        /// Contstructor
        /// </summary>
        /// <param name="text">info</param>
        /// <param name="action">action</param>
        public Rule(string text, RuleCheck action)
        {
            this.Text = text;
            this.Action = action;
        }
    }
    public  class TimeApiResponse
    {
        public int hour { get; set;}
    }
}

PasswordGame/PasswordGame/Controllers/GameController.cs
using Microsoft.AspNetCore.Mvc;
using PasswordGame.Models;

namespace PasswordGame.Controllers
{
	public class GameController : Controller
	{
		private GameViewModel _model = new GameViewModel();
		public IActionResult Index()
		{
			return View(_model);
		}

		/// <summary>
		/// Method GET
		/// </summary>
		/// <param name="password">passowrd</param>
		/// <returns>IActionResult</returns>
		public IActionResult CheckPassword(string password)
		{

			if(string.IsNullOrEmpty(password))
			{
				return View("Index");
			}

			List<string> results = new List<string>();
			string backColor = "primary";

			_model.HtmlResult = string.Empty;

			for (int i = 0; i < _model.LastRule; i++)
			{
				if(i >= _model.Rules.Count)
				{
					_model.IsPasswordComplete=true;
					results.Clear();
					results.Add(
						@$"
					<div style='height:25px;'y
					</div>
					<div class='card alert mt-3 align-self-center mx-auto alert-{backColor}'
						 style='width:fit-content; height: auto; padding:10px; max-width:500px;'>
					<a> Your password created <strong>{password}</strong></a>
					</div>"
						);
					break;
				}
				
				if (_model.Rules[i].Action(password))
				{
					_model.LastRule++;
					backColor= "success";
				}
				else{
					backColor= "danger";
				}
				results.Add(

					@$"
					<div style='height:25px;'y
					</div>
					<div class='card alert mt-3 align-self-center mx-auto alert-{backColor}'
						 style='width:fit-content; height: auto; padding:10px; max-width:500px;'>
					<a><strong>Правило {i + 1}:</strong> {_model.Rules[i].Text}</a>
					</div>"

				);
			}
			results.Reverse();
			_model.HtmlResult = string.Join("", results);
			return View("Index",_model);
		}
	}
}

PasswordGame/PasswordGame/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PasswordGame.Models;
using System.Diagnostics;

namespace PasswordGame.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult Privacy()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}
	}
}

PasswordGame/PasswordGame/Views/Game/Index.cshtml
    
@model GameViewModel

@{

}


<script>
    /**
    *
    */
    function resizeTextarea(textarea)
    {
        textarea.style.height = 'auto';
        textarea.style.height = textarea.scrollHeight + 'px';
    }
    function getQueryParam(name)
    {
        const urlParam = new URLSearchParams(window.location.search);
        return urlParam.get(name);
    }
</script>

@{
    if(!Model.IsPasswordComplete)
    {
        <div class="text-center container">

            <p>
                Enter password:
            </p>
            <br>
            <form action="/Game/CheckPassword" method="GET">
                <div class="d-flex " style="justify-content: center;
            gap: 3px;    flex-direction: column;
            align-content: center;
            align-items: center;">
                    <textarea name="password"
                              id="passwordTextarea"
                              style="overflow: hidden;
                    resize:none;
                    border-radius: 4px;
                    background-color: #e5e5e5;
                    "
                              oninput="resizeTextarea(this)"
                              cols=60
                              rows=1>
                    </textarea>

                    <input type="submit" class="btn btn-success ">

                </div>

            </form>
            <script>
                const passwordValue = getQueryParam("password");
                const textarea = document.getElementById("passwordTextarea");

                textarea.value = passwordValue;
            </script>
        </div>
    }


}
@Html.Raw(Model.HtmlResult)

@{
    if(Model.IsPasswordComplete)
    {
        <div class="container ">
            <div class="row " style="display: flex;
        flex-direction: row;
        padding-left: 0;
        margin-bottom: 0;
        list-style: none;
        align-items: center;
        justify-content: center;
        align-content: center;">
                <li class="nav-item col-md-6" style="width:17%">
                    <a asp-controller="Game" asp-action="Index" class="btn btn-success rounded nav-link text-white" style="width:100%">CHANGE</a>
                </li>
                <li class="nav-item col-md-6" style="width:12%">
                    <a asp-controller="Home" asp-action="Index" class="btn btn-primary rounded nav-link text-white" style="width:100%">SAVE</a>
                </li>
        </div>
         
        </div>
    }
}

PasswordGame/PasswordGame/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PasswordGame/PasswordGame/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PasswordGame</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PasswordGame.styles.css" asp-append-version="true" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse justify-content-center">
                    <ul class="navbar-nav ">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                                  <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">PasswordGame</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted position-absolute w-100 fixed-bottom text-center" >
        <div class="container">
            &copy; 2023 - PasswordGame - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>